# my_config.yaml

##########################################################################################

# LOGGING
logging:
  file_level: DEBUG
  console_level: DEBUG

##########################################################################################

# PATHS
data_dir:
  raw: data/raw/
  processed: data/processed/

img_dir: data/raw/images/
box_dir: data/raw/boxes/

img_path: data/raw/images/frame_000001.PNG
vid_path: data/processed/processed1.avi
output_path: reports/figures/result1.mp4

results: reports/

##########################################################################################
